-- ============================================================================
-- AGENT INTERACTION TRACKING SCHEMA
-- ============================================================================
-- Comprehensive tracking of all agent interactions, workflows, and data flows
-- during prompt generation sessions. Links to generation_runs and ai_agents.
-- ============================================================================

-- Table: agent_interactions
-- Core table tracking each agent's participation in a generation run
CREATE TABLE agent_interactions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    product_id UUID NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    generation_run_id BIGINT NOT NULL REFERENCES generation_runs(id) ON DELETE CASCADE,
    ai_agent_id UUID NOT NULL REFERENCES ai_agents(id) ON DELETE RESTRICT,
    interaction_sequence INTEGER NOT NULL,  -- Order in the workflow (1, 2, 3, ...)
    status VARCHAR(50) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'in_progress', 'completed', 'failed', 'skipped')),
    started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    execution_time_ms INTEGER,  -- Duration in milliseconds
    error_message TEXT,  -- If status = 'failed'
    error_details JSONB,  -- Extended error information
    retry_count INTEGER DEFAULT 0,
    metadata JSONB DEFAULT '{}'::jsonb,  -- Additional context (model params, config, etc.)
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_agent_interactions_product ON agent_interactions(product_id);
CREATE INDEX idx_agent_interactions_tenant ON agent_interactions(tenant_id);
CREATE INDEX idx_agent_interactions_generation_run ON agent_interactions(generation_run_id);
CREATE INDEX idx_agent_interactions_ai_agent ON agent_interactions(ai_agent_id);
CREATE INDEX idx_agent_interactions_status ON agent_interactions(status);
CREATE INDEX idx_agent_interactions_sequence ON agent_interactions(generation_run_id, interaction_sequence);
CREATE INDEX idx_agent_interactions_created ON agent_interactions(created_at);

-- Table: agent_interaction_libraries
-- Tracks which libraries (personas, scenarios, test cases, etc.) were accessed by each agent
CREATE TABLE agent_interaction_libraries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    product_id UUID NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
    agent_interaction_id UUID NOT NULL REFERENCES agent_interactions(id) ON DELETE CASCADE,
    library_type VARCHAR(50) NOT NULL CHECK (library_type IN ('persona', 'scenario', 'test_case', 'prompt', 'threat_vector', 'risk', 'harm', 'use_case', 'context_profile')),
    library_id UUID NOT NULL,  -- Polymorphic reference to library table
    library_name TEXT,  -- Denormalized for readability
    access_type VARCHAR(50) NOT NULL CHECK (access_type IN ('read', 'write', 'update', 'delete', 'filter')),
    item_count INTEGER DEFAULT 1,  -- Number of items accessed/created from this library
    access_details JSONB DEFAULT '{}'::jsonb,  -- Filters, parameters, selections
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_agent_interaction_libraries_interaction ON agent_interaction_libraries(agent_interaction_id);
CREATE INDEX idx_agent_interaction_libraries_product ON agent_interaction_libraries(product_id);
CREATE INDEX idx_agent_interaction_libraries_library_type ON agent_interaction_libraries(library_type);
CREATE INDEX idx_agent_interaction_libraries_created ON agent_interaction_libraries(created_at);

-- Table: agent_interaction_inputs
-- Stores input parameters and data provided to each agent interaction
CREATE TABLE agent_interaction_inputs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    product_id UUID NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
    agent_interaction_id UUID NOT NULL REFERENCES agent_interactions(id) ON DELETE CASCADE,
    input_key TEXT NOT NULL,  -- Parameter name (e.g., "prompt_text", "temperature", "max_tokens")
    input_type VARCHAR(50) NOT NULL CHECK (input_type IN ('string', 'number', 'boolean', 'json', 'array', 'reference')),
    input_value TEXT,  -- Serialized value or reference ID
    input_description TEXT,  -- Human-readable description
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_agent_interaction_inputs_interaction ON agent_interaction_inputs(agent_interaction_id);
CREATE INDEX idx_agent_interaction_inputs_product ON agent_interaction_inputs(product_id);
CREATE INDEX idx_agent_interaction_inputs_key ON agent_interaction_inputs(input_key);

-- Table: agent_interaction_outputs
-- Stores output data and results generated by each agent interaction
CREATE TABLE agent_interaction_outputs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    product_id UUID NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
    agent_interaction_id UUID NOT NULL REFERENCES agent_interactions(id) ON DELETE CASCADE,
    output_key TEXT NOT NULL,  -- Field name (e.g., "generated_prompt", "evaluation_score", "personas_created")
    output_type VARCHAR(50) NOT NULL CHECK (output_type IN ('string', 'number', 'boolean', 'json', 'array', 'reference')),
    output_value TEXT,  -- Serialized value or reference ID
    output_size_bytes INTEGER,  -- Size of output for large data tracking
    output_description TEXT,  -- Human-readable description
    quality_score FLOAT,  -- Optional quality metric (0-1)
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_agent_interaction_outputs_interaction ON agent_interaction_outputs(agent_interaction_id);
CREATE INDEX idx_agent_interaction_outputs_product ON agent_interaction_outputs(product_id);
CREATE INDEX idx_agent_interaction_outputs_key ON agent_interaction_outputs(output_key);

-- Table: agent_interaction_flow
-- Tracks data flow between agents in the workflow sequence
CREATE TABLE agent_interaction_flow (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    product_id UUID NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
    generation_run_id BIGINT NOT NULL REFERENCES generation_runs(id) ON DELETE CASCADE,
    source_agent_interaction_id UUID NOT NULL REFERENCES agent_interactions(id) ON DELETE CASCADE,
    target_agent_interaction_id UUID NOT NULL REFERENCES agent_interactions(id) ON DELETE CASCADE,
    flow_type VARCHAR(50) NOT NULL CHECK (flow_type IN ('sequential', 'conditional', 'parallel', 'feedback', 'refinement')),
    flow_sequence INTEGER NOT NULL,  -- Order of flow events
    data_exchanged JSONB,  -- What data was passed between agents
    transfer_timestamp TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    size_bytes INTEGER,  -- Size of data transferred
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_agent_interaction_flow_generation_run ON agent_interaction_flow(generation_run_id);
CREATE INDEX idx_agent_interaction_flow_source ON agent_interaction_flow(source_agent_interaction_id);
CREATE INDEX idx_agent_interaction_flow_target ON agent_interaction_flow(target_agent_interaction_id);
CREATE INDEX idx_agent_interaction_flow_product ON agent_interaction_flow(product_id);
CREATE INDEX idx_agent_interaction_flow_sequence ON agent_interaction_flow(generation_run_id, flow_sequence);

-- Table: agent_interaction_decisions
-- Tracks decision points and branches in agent workflows
CREATE TABLE agent_interaction_decisions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    product_id UUID NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
    agent_interaction_id UUID NOT NULL REFERENCES agent_interactions(id) ON DELETE CASCADE,
    decision_point TEXT NOT NULL,  -- What decision was made
    decision_type VARCHAR(50) NOT NULL CHECK (decision_type IN ('routing', 'filtering', 'retry', 'escalation', 'termination')),
    decision_criteria JSONB NOT NULL,  -- Conditions that led to this decision
    decision_result VARCHAR(50) NOT NULL,  -- Outcome of decision
    alternative_paths JSONB,  -- Other possible paths that could have been taken
    confidence_score FLOAT,  -- Confidence in the decision (0-1)
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_agent_interaction_decisions_interaction ON agent_interaction_decisions(agent_interaction_id);
CREATE INDEX idx_agent_interaction_decisions_product ON agent_interaction_decisions(product_id);
CREATE INDEX idx_agent_interaction_decisions_type ON agent_interaction_decisions(decision_type);

-- Table: agent_interaction_metrics
-- Captures performance and quality metrics for each interaction
CREATE TABLE agent_interaction_metrics (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    product_id UUID NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
    agent_interaction_id UUID NOT NULL REFERENCES agent_interactions(id) ON DELETE CASCADE,
    metric_name VARCHAR(100) NOT NULL,  -- e.g., "tokens_processed", "quality_score", "latency_ms"
    metric_value FLOAT NOT NULL,
    metric_unit VARCHAR(50),  -- e.g., "ms", "tokens", "score"
    metric_category VARCHAR(50) CHECK (metric_category IN ('performance', 'quality', 'cost', 'reliability')),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_agent_interaction_metrics_interaction ON agent_interaction_metrics(agent_interaction_id);
CREATE INDEX idx_agent_interaction_metrics_product ON agent_interaction_metrics(product_id);
CREATE INDEX idx_agent_interaction_metrics_name ON agent_interaction_metrics(metric_name);
CREATE INDEX idx_agent_interaction_metrics_category ON agent_interaction_metrics(metric_category);

-- ============================================================================
-- VIEWS FOR AGENT INTERACTION ANALYSIS
-- ============================================================================

-- View: vw_agent_workflow_summary
-- Complete view of agent interactions in a generation run
CREATE OR REPLACE VIEW vw_agent_workflow_summary AS
SELECT 
    gr.generation_run_id,
    gr.id as run_id,
    aa.agent_name,
    aa.agent_type,
    ai.interaction_sequence,
    ai.status,
    ai.started_at,
    ai.completed_at,
    ai.execution_time_ms,
    ai.error_message,
    COUNT(DISTINCT ail.id) as libraries_accessed,
    COUNT(DISTINCT aio_in.id) as inputs_provided,
    COUNT(DISTINCT aio_out.id) as outputs_generated,
    gr.created_at as run_created_at
FROM agent_interactions ai
JOIN generation_runs gr ON ai.generation_run_id = gr.id
JOIN ai_agents aa ON ai.ai_agent_id = aa.id
LEFT JOIN agent_interaction_libraries ail ON ai.id = ail.agent_interaction_id
LEFT JOIN agent_interaction_inputs aio_in ON ai.id = aio_in.agent_interaction_id
LEFT JOIN agent_interaction_outputs aio_out ON ai.id = aio_out.agent_interaction_id
GROUP BY gr.generation_run_id, gr.id, aa.agent_name, aa.agent_type, ai.interaction_sequence, ai.status, 
         ai.started_at, ai.completed_at, ai.execution_time_ms, ai.error_message, gr.created_at
ORDER BY gr.id DESC, ai.interaction_sequence ASC;

-- View: vw_agent_interaction_lineage
-- Traces data flow through agent interactions
CREATE OR REPLACE VIEW vw_agent_interaction_lineage AS
SELECT 
    gr.generation_run_id,
    aif.flow_sequence,
    source_agent.agent_name as source_agent,
    target_agent.agent_name as target_agent,
    aif.flow_type,
    aif.size_bytes,
    aif.transfer_timestamp,
    source_ai.interaction_sequence as source_sequence,
    target_ai.interaction_sequence as target_sequence
FROM agent_interaction_flow aif
JOIN generation_runs gr ON aif.generation_run_id = gr.id
JOIN agent_interactions source_ai ON aif.source_agent_interaction_id = source_ai.id
JOIN agent_interactions target_ai ON aif.target_agent_interaction_id = target_ai.id
JOIN ai_agents source_agent ON source_ai.ai_agent_id = source_agent.id
JOIN ai_agents target_agent ON target_ai.ai_agent_id = target_agent.id
ORDER BY gr.id DESC, aif.flow_sequence ASC;
